-- Supabase development schema for nss-ratings

CREATE TABLE IF NOT EXISTS public.mostActive (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "fetchedAt" timestamptz DEFAULT now() NOT NULL,
  symbol text NOT NULL,
  price numeric,
  volume bigint,
  "marketCap" bigint,
  "percentChange" numeric
);

CREATE TABLE IF NOT EXISTS public.screener_signals (
  signal_id text PRIMARY KEY,
  symbol text NOT NULL,
  direction text,
  strategy_name text,
  timeframe text,
  signal_bar_time timestamptz,
  current_price numeric,
  current_price_updated_at timestamptz,
  trigger_price numeric,
  signal_score numeric,
  signal_quality text,
  status text,
  price numeric,
  chg numeric,
  rvol numeric,
  vwap numeric,
  volume numeric,
  day_high numeric,
  day_low numeric,
  premarket_high numeric,
  premarket_low numeric,
  sw_high numeric,
  sw_low numeric,
  sig_high numeric,
  sig_low numeric,
  at_val numeric,
  atr numeric,
  score_reasons text,
  duplicate_of_signal_id text,
  confirmation_count integer,
  confirmations text[],
  outcome_15m numeric,
  outcome_30m numeric,
  outcome_60m numeric,
  max_favorable_move numeric,
  max_adverse_move numeric,
  raw_alert_payload jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  entry_type text,
  entry_price_est numeric,
  entry_zone_low numeric,
  entry_zone_high numeric,
  stop_price numeric,
  target1_price numeric,
  target2_price numeric,
  target3_price numeric,
  close_price_est numeric,
  risk_per_share numeric,
  reward_to_risk_t1 numeric,
  reward_to_risk_t2 numeric,
  reward_to_risk_t3 numeric,
  trade_plan_quality text,
  trade_plan_reason text,
  invalidation_reason text,
  recent_swing_high numeric,
  recent_swing_low numeric,
  signal_candle_high numeric,
  signal_candle_low numeric,
  alphatrend_at_signal numeric
);

-- Optional indexes for query performance
CREATE INDEX IF NOT EXISTS idx_screener_signals_symbol ON public.screener_signals(symbol);
CREATE INDEX IF NOT EXISTS idx_screener_signals_status ON public.screener_signals(status);
CREATE INDEX IF NOT EXISTS idx_screener_signals_signal_bar_time ON public.screener_signals(signal_bar_time);
